#!/bin/bash
# http://stackoverflow.com/questions/151677/tool-for-adding-license-headers-to-source-files
DIRECTORY=$1
for i in $DIRECTORY/*.py 
do
  if ! grep -q Copyright $i
  then
    cat copyright.py $i >$i.new && mv $i.new $i
    echo $i
  fi
done
