OPTS = -Wall
CC = gcc
LDFLAGS = -Lecos -lm
CFLAGS = -Wall
INCLUDE = -Iecos/include  -Iecos/external/SuiteSparse_config

example_problem: solver_intf.o codegen.o linop.o param.o example_problem.o ecos/libecos.a
	$(CC) $(CFLAGS) solver_intf.o codegen.o linop.o param.o example_problem.o -lecos -o $@ $(LDFLAGS) 

solver_intf.o: solver_intf.c
	$(CC) $(CFLAGS) $(INCLUDE) -c $<

codegen.o: codegen.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDE) -c $<

linop.o: linop.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDE) -c $<

param.o: param.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDE) -c $<

example_problem.o: example_problem.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDE) -c $<

ecos/libecos.a:
	cd ecos && make libecos.a

.PHONY: clean
clean:
	cd ecos && make clean
	rm -rf *.o example_problem

.PHONY: re
re: clean example_problem
