OPTS = -Wall
CC = gcc
LDFLAGS = -lm {{LD_FLAGS}} 
LIB_DIR = {{LIB_DIR}}

{% if debug %}
CFLAGS = -Wall -g
{% else %}
CFLAGS = -Wall
{% endif %}

{{ INCLUDES }}


example_problem: solver_intf.o codegen.o expr_handler.o example_problem.o $(LIB_DIR)
	$(CC) $(CFLAGS) solver_intf.o codegen.o expr_handler.o example_problem.o -o $@ $(LDFLAGS) 

solver_intf.o: solver_intf.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $<

codegen.o: codegen.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDES) -c $<

expr_handler.o: expr_handler.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDES) -c $<

example_problem.o: example_problem.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDES) -c $<

atoms.o: atoms.c codegen.h
	$(CC) $(CFLAGS) $(INCLUDES) -c $<


{{ BUILD }}


.PHONY: clean
clean:
	{{ CLEAN }}
	rm -rf *.o example_problem

.PHONY: re
re: clean example_problem
